version: '3'

services:
    pizza-api:
        image: ambientum/node:16
        container_name: pizza-api
        command: bash -c "npm i && npm run dev"
        ports:
            - '${PORT:-3000}:${PORT:-3000}'
        volumes:
            - .:/var/www/app
